### ISSUE TITLE
Button on Confirmation page should link to correct order detail page

### ISSUE THREAD

**Issue by cebed** [tieraid-app/tieraid-app.github.io#66]

**Comment by cebed** [comment]
@acreations as it is now we navigate to order view for customer if a customer submitted order. And navigate to order view for supplier if supplier added order?

Should we have this or should we just navigate to / ?

**Comment by cebed** [comment]
<img width="1006" alt="image" src="https://github.com/tieraid-app/tieraid-app.github.io/assets/36077080/cc9b1e68-2b37-415b-98b0-a55806d1f48d">

**Comment by acreations** [comment]
I think you always navigate to customer order view since supplier that places an order is a hybrid one

**Comment by cebed** [comment]
Alright done now
