### ISSUE TITLE
Search does not work for my products

### ISSUE THREAD

**Issue by cebed** [tieraid-app/tieraid-app.github.io#74]
@JohnnyJai please update how to reproduce bug

**Comment by JohnnyJai** [comment]
> @JohnnyJai please update how to reproduce bug

Try to search for apple, you still get banana, it is a BE bug.

**Comment by cebed** [comment]
Please close the issue and open the issue in BE instead

Med vänlig hälsning, Daniel Cebe
________________________________
Från: Johnny Ha ***@***.***>
Skickat: Sunday, September 17, 2023 8:44:16 PM
Till: tieraid-app/tieraid-app.github.io ***@***.***>
Kopia: cebed ***@***.***>; Author ***@***.***>
Ämne: Re: [tieraid-app/tieraid-app.github.io] Search does not work for my products (Issue #74)


@JohnnyJai<https://github.com/JohnnyJai> please update how to reproduce bug

Try to search for apple, you still get banana, it is a BE bug.
