### ISSUE TITLE
Change favicon

### ISSUE THREAD

**Issue by cebed** [tieraid-app/tieraid-app.github.io#85]
### Description
The current favicon on the website needs to be updated to align with the latest design or branding changes.

The current favicon no longer aligns with the visual identity of the website. We need to replace it with the new favicon to ensure a consistent and updated look for the site.

<img width="815" alt="image" src="https://github.com/tieraid-app/tieraid-app.github.io/assets/36077080/48f7d1bf-6395-491b-aac9-87e1a5e2f46a">

**Comment by acreations** [comment]
I think it is not indexed again since we have already updated it 

<img width="93" alt="image" src="https://github.com/tieraid-app/tieraid-app.github.io/assets/450741/aa63d059-70f9-4933-b05c-918291753dc7">
